### ISSUE TITLE
NodeSelectorService Development for Retrieving Nodes from Graph Database

### ISSUE THREAD

**Issue by LucaFalasca** [LucaFalasca/Bus4You#106]
US: #105

Descrizione:
Sviluppare la parte del microservizio NodeSelectorService che prende i nodi dal db a grafo

**Comment by StefanAdrianHuma** [comment]
E' un vostro errore oppure appare solo a me?

NodeSelectorService:
2023-07-05 19:47:13 {'vehicles': [{'id': 0, 'capacity': [8], 'profile': 'driving-car', 'start': [12.527504, 41.837339]}], 'shipments': [{'amount': [1], 'pickup': {'id': 0, 'time_windows': [[0, 2400]], 'location': [12.527504, 41.837339]}, 'delivery': {'id': 1, 'time_windows': [[0, 2400]], 'location': [12.627504, 41.837339]}}, {'amount': [1], 'pickup': {'id': 2, 'time_windows': [[4800, 100000]], 'location': [12.427504, 41.837339]}, 'delivery': {'id': 3, 'time_windows': [[4800, 100000]], 'location': [12.527504, 41.737339]}}, {'amount': [1], 'pickup': {'id': 4, 'time_windows': [[4200, 100000]], 'location': [12.547504, 41.737339]}, 'delivery': {'id': 5, 'time_windows': [[4200, 100000]], 'location': [12.327504, 41.767339]}}], 'options': {'g': True}}
2023-07-05 19:47:13 Traceback (most recent call last):
2023-07-05 19:47:13   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 200, in _new_conn
2023-07-05 19:47:13     sock = connection.create_connection(
2023-07-05 19:47:13            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-05 19:47:13   File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
2023-07-05 19:47:13     raise err
2023-07-05 19:47:13   File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
2023-07-05 19:47:13     sock.connect(sa)
2023-07-05 19:47:13 ConnectionRefusedError: [Errno 111] Connection refused
2023-07-05 19:47:13 
2023-07-05 19:47:13 The above exception was the direct cause of the following exception:
2023-07-05 19:47:13 
2023-07-05 19:47:13 Traceback (most recent call last):
2023-07-05 19:47:13   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
2023-07-05 19:47:13     response = self._make_request(
2023-07-05 19:47:13                ^^^^^^^^^^^^^^^^^^^
2023-07-05 19:47:13   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 496, in _make_request
2023-07-05 19:47:13     conn.request(
2023-07-05 19:47:13   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 388, in request
2023-07-05 19:47:13     self.endheaders()
2023-07-05 19:47:13   File "/usr/local/lib/python3.11/http/client.py", line 1281, in endheaders
2023-07-05 19:47:13     self._send_output(message_body, encode_chunked=encode_chunked)
2023-07-05 19:47:13   File "/usr/local/lib/python3.11/http/client.py", line 1041, in _send_output
2023-07-05 19:47:13     self.send(msg)
2023-07-05 19:47:13   File "/usr/local/lib/python3.11/http/client.py", line 979, in send
2023-07-05 19:47:13     self.connect()
2023-07-05 19:47:13   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 236, in connect
2023-07-05 19:47:13     self.sock = self._new_conn()
2023-07-05 19:47:13                 ^^^^^^^^^^^^^^^^
2023-07-05 19:47:13   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 215, in _new_conn
2023-07-05 19:47:13     raise NewConnectionError(
2023-07-05 19:47:13 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f4f49cfe4d0>: Failed to establish a new connection: [Errno 111] Connection refused
2023-07-05 19:47:13 
2023-07-05 19:47:13 The above exception was the direct cause of the following exception:
2023-07-05 19:47:13 
2023-07-05 19:47:13 Traceback (most recent call last):
2023-07-05 19:47:13   File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
2023-07-05 19:47:13     resp = conn.urlopen(
2023-07-05 19:47:13            ^^^^^^^^^^^^^
2023-07-05 19:47:13   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
2023-07-05 19:47:13     retries = retries.increment(
2023-07-05 19:47:13               ^^^^^^^^^^^^^^^^^^
2023-07-05 19:47:13   File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
2023-07-05 19:47:13     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
2023-07-05 19:47:13     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-05 19:47:13 urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4f49cfe4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-07-05 19:47:13 
2023-07-05 19:47:13 During handling of the above exception, another exception occurred:
2023-07-05 19:47:13 
2023-07-05 19:47:13 Traceback (most recent call last):
2023-07-05 19:47:13   File "/app/OrsDao.py", line 168, in <module>
2023-07-05 19:47:13     r1 = make_route(s1.pickup, [s1, s2, s3])
2023-07-05 19:47:13          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-05 19:47:13   File "/app/OrsDao.py", line 87, in make_route
2023-07-05 19:47:13     data = requests.post(url, json = body).json()
2023-07-05 19:47:13            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-05 19:47:13   File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 115, in post
2023-07-05 19:47:13     return request("post", url, data=data, json=json, **kwargs)
2023-07-05 19:47:13            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-05 19:47:13   File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
2023-07-05 19:47:13     return session.request(method=method, url=url, **kwargs)
2023-07-05 19:47:13            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-05 19:47:13   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
2023-07-05 19:47:13     resp = self.send(prep, **send_kwargs)
2023-07-05 19:47:13            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-05 19:47:13   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
2023-07-05 19:47:13     r = adapter.send(request, **kwargs)
2023-07-05 19:47:13         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-05 19:47:13   File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
2023-07-05 19:47:13     raise ConnectionError(e, request=request)
2023-07-05 19:47:13 requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4f49cfe4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by LucaFalasca** [comment]
@StefanAdrianHuma in pratica mi ero dimenticato di cambiare una configurazione del docker file che usavo per fare delle prove. Ora dovrebbe essere tutto ok
